### ISSUE TITLE
messengerBOT Endpoint

### ISSUE THREAD

**Issue by lambare** [botmasterai/node-red-contrib-botmaster#1]
I am trying to set up a bot but  i'm stuck in the following point in the relation with facebook and the botmaster.

Facebook subscription page
==================
URL webhook
https://ceedXXec.ngrok.io/facebook                                         (red alarm)
verify token
EAAPhZCtci1zABAPZCYj59tPEeWzdkZCrjqZBn98dqTVTqqHIlsFDVzBhHywew9NuCSeJWi..........................

on botmaster.
===============
Name          :xamplebot
Verify Token:dontcare
Page token: APhZCtci1zABAPZCYj59tPEeWzdkZCrjqZBn98dqTVTqqHIlsFDVzBhHywew9NuCSeJWi...............
App Secret: cbdd4702d880b0fedd3cb8f399999999
Endpoint:    /facebook

on ngrok console
==========

Session Status                online
Version                       2.1.17
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://ceedZZec.ngrok.io -> 127.0.0.1:1880
Forwarding                    https://ceedZZec.ngrok.io -> 128.0.0.1:1880

Connections                   ttl     opn     rt1     rt5     p50     p90
                              7       0       0.04    0.01    0.45    0.52

HTTP Requests
-------------

GET /facebook                  404 Not Found
GET /facebook                  404 Not Found
GET /facebook                  404 Not Found

Issue:
There is no way to fill up the subscription page on facebook, apears that the bot application don't answer the callback.
Debug does not show anything.

What am i doing wrong?
How can y test the callback on the node-red/botmaster?

Node-RED version: v0.16.2
Node.js  version: v6.10.0
Linux 3.10.0-514.el7.x86_64 x64 LE
The flow was imported from github/botmaster.

Regards.
rv

**Comment by lambare** [comment]
sorry..
Forwarding https://ceedZZec.ngrok.io -> 127.0.0.1:1880

**Comment by jwickens** [comment]
Hi @lambare were you able to solve your problem?

Each bot type's webhook is actually set under the name of the bot so for facebook messenger its 

`/messenger/facebook`

I will try to clarify this in the node-red help for future releases.

**Comment by lambare** [comment]
Yes, thanks for your interest.
Regards.
rv

2017-04-15 19:56 GMT-04:00 Jonathan R Wickens <notifications@github.com>:
