### ISSUE TITLE
Failed to show nodes and start the server

### ISSUE THREAD

**Issue by mavericklam** [botmasterai/node-red-contrib-botmaster#2]
Hi there! I tried this lib and found that there are mismatches on name in the package.json file with the node's js file, therefore it was failed to display the nodes in the node-red panel. Also, I found the server can not been start(or I should say the endpoint can not be listened after I config the messenger node correctly). Hope to fix this in the next version

**Comment by jwickens** [comment]
Hi this has been fixed in v0.5.2
